import { faker } from '@faker-js/faker';
import { 
  User, Project, Task, Skill, Nudge, 
  WorkloadEntry, AssignmentSuggestion, Scenario,
  TaskStatus, TaskPriority, NudgeType, NudgeSeverity
} from '@/types';

// Configure faker for consistent data
faker.seed(12345);

// ===== REALISTIC TEAM DATA =====
export const createRealisticTeam = (): User[] => {
  return [
    {
      id: 'user-sarah',
      email: 'sarah.chen@digitalcraft.com',
      name: 'Sarah Chen',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      role: 'pm',
      hourlyRate: 85,
      timezone: 'America/Los_Angeles',
    },
    {
      id: 'user-mike',
      email: 'mike.rodriguez@digitalcraft.com',
      name: 'Mike Rodriguez',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      role: 'admin',
      hourlyRate: 95,
      timezone: 'America/New_York',
    },
    {
      id: 'user-alex',
      email: 'alex.thompson@digitalcraft.com',
      name: 'Alex Thompson',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
      role: 'member',
      hourlyRate: 75,
      timezone: 'America/Chicago',
    },
    {
      id: 'user-emma',
      email: 'emma.wilson@digitalcraft.com',
      name: 'Emma Wilson',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
      role: 'member',
      hourlyRate: 80,
      timezone: 'Europe/London',
    },
    {
      id: 'user-james',
      email: 'james.kim@digitalcraft.com',
      name: 'James Kim',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
      role: 'member',
      hourlyRate: 90,
      timezone: 'America/Los_Angeles',
    },
    {
      id: 'user-lisa',
      email: 'lisa.park@digitalcraft.com',
      name: 'Lisa Park',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
      role: 'member',
      hourlyRate: 70,
      timezone: 'America/Toronto',
    },
    {
      id: 'user-david',
      email: 'david.martinez@digitalcraft.com',
      name: 'David Martinez',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
      role: 'member',
      hourlyRate: 78,
      timezone: 'America/Mexico_City',
    },
    {
      id: 'user-rachel',
      email: 'rachel.green@digitalcraft.com',
      name: 'Rachel Green',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel',
      role: 'member',
      hourlyRate: 82,
      timezone: 'America/New_York',
    },
  ];
};

// ===== SKILLS CATALOG =====
export const createSkillsCatalog = (): Skill[] => {
  return [
    { id: 'skill-react', name: 'React', category: 'Frontend' },
    { id: 'skill-ts', name: 'TypeScript', category: 'Frontend' },
    { id: 'skill-next', name: 'Next.js', category: 'Frontend' },
    { id: 'skill-tailwind', name: 'Tailwind CSS', category: 'Frontend' },
    { id: 'skill-node', name: 'Node.js', category: 'Backend' },
    { id: 'skill-python', name: 'Python', category: 'Backend' },
    { id: 'skill-postgres', name: 'PostgreSQL', category: 'Backend' },
    { id: 'skill-graphql', name: 'GraphQL', category: 'Backend' },
    { id: 'skill-figma', name: 'Figma', category: 'Design' },
    { id: 'skill-ui', name: 'UI Design', category: 'Design' },
    { id: 'skill-ux', name: 'UX Research', category: 'Design' },
    { id: 'skill-motion', name: 'Motion Design', category: 'Design' },
    { id: 'skill-aws', name: 'AWS', category: 'DevOps' },
    { id: 'skill-docker', name: 'Docker', category: 'DevOps' },
    { id: 'skill-k8s', name: 'Kubernetes', category: 'DevOps' },
    { id: 'skill-pm', name: 'Project Management', category: 'Management' },
    { id: 'skill-seo', name: 'SEO', category: 'Marketing' },
    { id: 'skill-content', name: 'Content Strategy', category: 'Marketing' },
    { id: 'skill-threejs', name: 'Three.js', category: 'Frontend' },
    { id: 'skill-rust', name: 'Rust', category: 'Backend' },
  ];
};

// Team member skills mapping
export const teamSkills: Record<string, { skillId: string; proficiency: 1 | 2 | 3 | 4 }[]> = {
  'user-sarah': [
    { skillId: 'skill-pm', proficiency: 4 },
    { skillId: 'skill-figma', proficiency: 3 },
  ],
  'user-mike': [
    { skillId: 'skill-react', proficiency: 4 },
    { skillId: 'skill-ts', proficiency: 4 },
    { skillId: 'skill-node', proficiency: 3 },
    { skillId: 'skill-aws', proficiency: 4 },
  ],
  'user-alex': [
    { skillId: 'skill-react', proficiency: 3 },
    { skillId: 'skill-ts', proficiency: 3 },
    { skillId: 'skill-next', proficiency: 4 },
    { skillId: 'skill-tailwind', proficiency: 4 },
  ],
  'user-emma': [
    { skillId: 'skill-figma', proficiency: 4 },
    { skillId: 'skill-ui', proficiency: 4 },
    { skillId: 'skill-ux', proficiency: 3 },
    { skillId: 'skill-motion', proficiency: 3 },
  ],
  'user-james': [
    { skillId: 'skill-node', proficiency: 4 },
    { skillId: 'skill-python', proficiency: 4 },
    { skillId: 'skill-postgres', proficiency: 4 },
    { skillId: 'skill-graphql', proficiency: 3 },
  ],
  'user-lisa': [
    { skillId: 'skill-react', proficiency: 3 },
    { skillId: 'skill-ts', proficiency: 2 },
    { skillId: 'skill-seo', proficiency: 4 },
    { skillId: 'skill-content', proficiency: 3 },
  ],
  'user-david': [
    { skillId: 'skill-docker', proficiency: 4 },
    { skillId: 'skill-k8s', proficiency: 3 },
    { skillId: 'skill-aws', proficiency: 3 },
    { skillId: 'skill-node', proficiency: 2 },
  ],
  'user-rachel': [
    { skillId: 'skill-figma', proficiency: 3 },
    { skillId: 'skill-ui', proficiency: 3 },
    { skillId: 'skill-content', proficiency: 4 },
    { skillId: 'skill-seo', proficiency: 3 },
  ],
};

// ===== REALISTIC PROJECTS =====
export const createRealisticProjects = (): Project[] => {
  return [
    {
      id: 'proj-ecommerce',
      name: 'E-Commerce Platform Redesign',
      description: 'Complete overhaul of client\'s e-commerce platform with modern tech stack. Includes new checkout flow, product catalog, and admin dashboard.',
      status: 'active',
      priority: 95,
      startDate: new Date('2026-01-15'),
      targetEndDate: new Date('2026-04-30'),
      healthScore: 72,
      progress: 45,
    },
    {
      id: 'proj-mobile',
      name: 'Fitness App Mobile Launch',
      description: 'Native mobile application for iOS and Android featuring workout tracking, nutrition logging, and social features.',
      status: 'active',
      priority: 88,
      startDate: new Date('2026-02-01'),
      targetEndDate: new Date('2026-05-15'),
      healthScore: 45,
      progress: 25,
    },
    {
      id: 'proj-saas',
      name: 'SaaS Dashboard Analytics',
      description: 'Advanced analytics dashboard for B2B SaaS platform with real-time data visualization and reporting features.',
      status: 'active',
      priority: 75,
      startDate: new Date('2026-02-10'),
      targetEndDate: new Date('2026-04-20'),
      healthScore: 85,
      progress: 60,
    },
    {
      id: 'proj-marketing',
      name: 'Marketing Website Revamp',
      description: 'Redesign of company marketing website with improved SEO, performance, and conversion optimization.',
      status: 'active',
      priority: 70,
      startDate: new Date('2026-02-15'),
      targetEndDate: new Date('2026-03-30'),
      healthScore: 90,
      progress: 80,
    },
    {
      id: 'proj-internal',
      name: 'Internal Project Management Tool',
      description: 'Custom project management solution for internal team with resource allocation and time tracking.',
      status: 'paused',
      priority: 50,
      startDate: new Date('2025-12-01'),
      targetEndDate: new Date('2026-03-01'),
      healthScore: 30,
      progress: 40,
    },
  ];
};

// ===== REALISTIC TASKS =====
export const createRealisticTasks = (): Task[] => {
  const tasks: Task[] = [
    // E-Commerce Project Tasks
    {
      id: 'task-ec-1',
      projectId: 'proj-ecommerce',
      title: 'Design System Architecture',
      description: 'Create comprehensive design system with component library, tokens, and documentation.',
      status: 'done',
      priority: 'high',
      priorityScore: 90,
      businessValue: 95,
      estimatedHours: 40,
      actualHours: 42,
      dueDate: new Date('2026-02-01'),
      assigneeId: 'user-emma',
      requiredSkills: ['skill-figma', 'skill-ui'],
      isMilestone: true,
      isCriticalPath: true,
      riskScore: 10,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-ec-2',
      projectId: 'proj-ecommerce',
      title: 'Backend API Development',
      description: 'Build RESTful APIs for product catalog, cart, and order management.',
      status: 'in_progress',
      priority: 'critical',
      priorityScore: 95,
      businessValue: 100,
      estimatedHours: 80,
      dueDate: new Date('2026-03-15'),
      assigneeId: 'user-james',
      requiredSkills: ['skill-node', 'skill-postgres', 'skill-graphql'],
      isMilestone: false,
      isCriticalPath: true,
      riskScore: 65,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-ec-3',
      projectId: 'proj-ecommerce',
      title: 'Frontend Product Catalog',
      description: 'Implement product listing, filtering, and detail pages with SSR.',
      status: 'in_progress',
      priority: 'high',
      priorityScore: 85,
      businessValue: 90,
      estimatedHours: 60,
      dueDate: new Date('2026-03-20'),
      assigneeId: 'user-alex',
      requiredSkills: ['skill-react', 'skill-next', 'skill-ts'],
      isMilestone: false,
      isCriticalPath: true,
      riskScore: 45,
      hierarchyLevel: 1,
      dependencies: ['task-ec-1'],
      blockedBy: [],
    },
    {
      id: 'task-ec-4',
      projectId: 'proj-ecommerce',
      title: 'Checkout Flow Implementation',
      description: 'Build multi-step checkout with payment integration and order confirmation.',
      status: 'ready',
      priority: 'critical',
      priorityScore: 95,
      businessValue: 100,
      estimatedHours: 50,
      dueDate: new Date('2026-04-05'),
      assigneeId: undefined,
      requiredSkills: ['skill-react', 'skill-ts', 'skill-node'],
      isMilestone: true,
      isCriticalPath: true,
      riskScore: 75,
      hierarchyLevel: 1,
      dependencies: ['task-ec-2'],
      blockedBy: ['task-ec-2'],
    },
    {
      id: 'task-ec-5',
      projectId: 'proj-ecommerce',
      title: 'Admin Dashboard',
      description: 'Create admin interface for product management, orders, and analytics.',
      status: 'backlog',
      priority: 'medium',
      priorityScore: 70,
      businessValue: 80,
      estimatedHours: 55,
      dueDate: new Date('2026-04-20'),
      assigneeId: 'user-lisa',
      requiredSkills: ['skill-react', 'skill-ts'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 30,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    
    // Fitness App Tasks
    {
      id: 'task-fit-1',
      projectId: 'proj-mobile',
      title: 'Mobile App UI Design',
      description: 'Design all screens for iOS and Android following platform guidelines.',
      status: 'in_progress',
      priority: 'high',
      priorityScore: 88,
      businessValue: 90,
      estimatedHours: 70,
      dueDate: new Date('2026-03-01'),
      assigneeId: 'user-emma',
      requiredSkills: ['skill-figma', 'skill-ui', 'skill-motion'],
      isMilestone: true,
      isCriticalPath: true,
      riskScore: 40,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-fit-2',
      projectId: 'proj-mobile',
      title: 'Workout Tracking API',
      description: 'Backend services for workout tracking, exercise database, and progress analytics.',
      status: 'in_progress',
      priority: 'high',
      priorityScore: 85,
      businessValue: 85,
      estimatedHours: 65,
      dueDate: new Date('2026-03-10'),
      assigneeId: 'user-james',
      requiredSkills: ['skill-python', 'skill-postgres'],
      isMilestone: false,
      isCriticalPath: true,
      riskScore: 55,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-fit-3',
      projectId: 'proj-mobile',
      title: 'Social Features Implementation',
      description: 'Friend connections, activity sharing, and leaderboards.',
      status: 'backlog',
      priority: 'medium',
      priorityScore: 60,
      businessValue: 70,
      estimatedHours: 45,
      dueDate: new Date('2026-04-15'),
      assigneeId: undefined,
      requiredSkills: ['skill-react', 'skill-ts', 'skill-threejs'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 80,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-fit-4',
      projectId: 'proj-mobile',
      title: '3D Exercise Animations',
      description: 'Interactive 3D models showing proper exercise form and technique.',
      status: 'backlog',
      priority: 'medium',
      priorityScore: 65,
      businessValue: 75,
      estimatedHours: 80,
      dueDate: new Date('2026-04-20'),
      assigneeId: undefined,
      requiredSkills: ['skill-threejs', 'skill-motion'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 90,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    
    // SaaS Dashboard Tasks
    {
      id: 'task-saas-1',
      projectId: 'proj-saas',
      title: 'Data Pipeline Setup',
      description: 'ETL pipeline for aggregating user events and business metrics.',
      status: 'done',
      priority: 'high',
      priorityScore: 90,
      businessValue: 95,
      estimatedHours: 50,
      actualHours: 48,
      dueDate: new Date('2026-02-28'),
      assigneeId: 'user-david',
      requiredSkills: ['skill-python', 'skill-aws', 'skill-docker'],
      isMilestone: false,
      isCriticalPath: true,
      riskScore: 20,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-saas-2',
      projectId: 'proj-saas',
      title: 'Real-time Analytics Widgets',
      description: 'Live dashboard widgets with WebSocket connections for real-time updates.',
      status: 'in_progress',
      priority: 'high',
      priorityScore: 85,
      businessValue: 90,
      estimatedHours: 55,
      dueDate: new Date('2026-03-25'),
      assigneeId: 'user-alex',
      requiredSkills: ['skill-react', 'skill-ts', 'skill-graphql'],
      isMilestone: false,
      isCriticalPath: true,
      riskScore: 35,
      hierarchyLevel: 1,
      dependencies: ['task-saas-1'],
      blockedBy: [],
    },
    {
      id: 'task-saas-3',
      projectId: 'proj-saas',
      title: 'Report Builder Feature',
      description: 'Custom report creation tool with drag-and-drop interface.',
      status: 'ready',
      priority: 'medium',
      priorityScore: 70,
      businessValue: 75,
      estimatedHours: 60,
      dueDate: new Date('2026-04-10'),
      assigneeId: 'user-mike',
      requiredSkills: ['skill-react', 'skill-ts'],
      isMilestone: true,
      isCriticalPath: false,
      riskScore: 40,
      hierarchyLevel: 1,
      dependencies: ['task-saas-1'],
      blockedBy: [],
    },
    
    // Marketing Website Tasks
    {
      id: 'task-web-1',
      projectId: 'proj-marketing',
      title: 'Homepage Redesign',
      description: 'New homepage with improved messaging, social proof, and CTA optimization.',
      status: 'in_progress',
      priority: 'high',
      priorityScore: 80,
      businessValue: 85,
      estimatedHours: 40,
      dueDate: new Date('2026-03-10'),
      assigneeId: 'user-lisa',
      requiredSkills: ['skill-react', 'skill-tailwind', 'skill-seo'],
      isMilestone: false,
      isCriticalPath: true,
      riskScore: 25,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-web-2',
      projectId: 'proj-marketing',
      title: 'Blog Platform Migration',
      description: 'Migrate blog to new CMS with improved SEO and performance.',
      status: 'review',
      priority: 'medium',
      priorityScore: 65,
      businessValue: 70,
      estimatedHours: 30,
      dueDate: new Date('2026-03-05'),
      assigneeId: 'user-rachel',
      requiredSkills: ['skill-content', 'skill-seo'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 15,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-web-3',
      projectId: 'proj-marketing',
      title: 'Case Studies Section',
      description: 'New case study pages with interactive elements and client testimonials.',
      status: 'in_progress',
      priority: 'medium',
      priorityScore: 60,
      businessValue: 65,
      estimatedHours: 35,
      dueDate: new Date('2026-03-20'),
      assigneeId: 'user-rachel',
      requiredSkills: ['skill-content', 'skill-figma'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 30,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    
    // Internal Tool Tasks
    {
      id: 'task-int-1',
      projectId: 'proj-internal',
      title: 'Time Tracking Module',
      description: 'Internal time tracking with project allocation and reporting.',
      status: 'review',
      priority: 'low',
      priorityScore: 45,
      businessValue: 60,
      estimatedHours: 40,
      dueDate: new Date('2026-02-28'),
      assigneeId: 'user-alex',
      requiredSkills: ['skill-react', 'skill-ts'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 20,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
    {
      id: 'task-int-2',
      projectId: 'proj-internal',
      title: 'Resource Planning View',
      description: 'Calendar view for resource allocation and capacity planning.',
      status: 'backlog',
      priority: 'low',
      priorityScore: 40,
      businessValue: 55,
      estimatedHours: 50,
      dueDate: new Date('2026-03-15'),
      assigneeId: undefined,
      requiredSkills: ['skill-react', 'skill-ts'],
      isMilestone: false,
      isCriticalPath: false,
      riskScore: 35,
      hierarchyLevel: 1,
      dependencies: [],
      blockedBy: [],
    },
  ];
  
  return tasks;
};

// ===== REALISTIC NUDGES (All 7 Types) =====
export const createRealisticNudges = (): Nudge[] => {
  return [
    // 1. OVERLOAD - Emma is overallocated
    {
      id: 'nudge-1',
      type: 'overload' as NudgeType,
      severity: 'high' as NudgeSeverity,
      title: 'Emma Wilson is overallocated at 125%',
      description: 'Emma has 75 hours assigned this week across 3 projects, exceeding her 40-hour capacity.',
      relatedProjectId: 'proj-mobile',
      relatedTaskId: 'task-fit-1',
      relatedPersonId: 'user-emma',
      aiExplanation: 'Based on current assignments, Emma is scheduled for 75 hours this week: 40h on Fitness App UI Design, 25h on E-Commerce design reviews, and 10h on marketing website consultation. This is unsustainable and increases burnout risk.',
      suggestedAction: 'Reassign Marketing Website consultation to Rachel',
      status: 'unread',
      createdAt: new Date('2026-02-21T09:30:00'),
    },
    
    // 2. DELAY_RISK - Backend API is behind schedule
    {
      id: 'nudge-2',
      type: 'delay_risk' as NudgeType,
      severity: 'high' as NudgeSeverity,
      title: 'Backend API Development at risk of missing deadline',
      description: 'Task is 30% complete with 50% of time elapsed. Current pace suggests 5-day delay.',
      relatedProjectId: 'proj-ecommerce',
      relatedTaskId: 'task-ec-2',
      relatedPersonId: 'user-james',
      aiExplanation: 'James has completed 24 hours of the 80-hour estimate, but the sprint is halfway through. At current velocity, this will finish 5 days late, blocking the critical Checkout Flow task.',
      suggestedAction: 'Assign Lisa to support API development',
      status: 'unread',
      createdAt: new Date('2026-02-21T10:15:00'),
    },
    
    // 3. SKILL_GAP - Three.js task unassigned
    {
      id: 'nudge-3',
      type: 'skill_gap' as NudgeType,
      severity: 'medium' as NudgeSeverity,
      title: 'No team member has Three.js expertise',
      description: 'Fitness App requires 3D exercise animations but no one is proficient in Three.js.',
      relatedProjectId: 'proj-mobile',
      relatedTaskId: 'task-fit-4',
      aiExplanation: 'The 3D Exercise Animations task requires Three.js proficiency (level 3+). Reviewed all team skills: Alex (React/Next.js), Emma (Design), James (Backend), Lisa (Frontend/SEO), David (DevOps), Rachel (Content/Design). None have Three.js experience.',
      suggestedAction: 'Hire Three.js contractor or simplify to 2D animations',
      status: 'unread',
      createdAt: new Date('2026-02-20T16:45:00'),
    },
    
    // 4. UNASSIGNED - Critical checkout flow
    {
      id: 'nudge-4',
      type: 'unassigned' as NudgeType,
      severity: 'high' as NudgeSeverity,
      title: 'Critical Checkout Flow task is unassigned',
      description: 'High-priority e-commerce task has no assignee and is blocking 3 other tasks.',
      relatedProjectId: 'proj-ecommerce',
      relatedTaskId: 'task-ec-4',
      relatedPersonId: undefined,
      aiExplanation: 'The Checkout Flow Implementation is on the critical path with a due date of April 5th. It\'s currently unassigned and blocking Frontend integration testing, Payment gateway setup, and Order confirmation email tasks.',
      suggestedAction: 'Assign to Mike (92% match) or Alex (85% match)',
      status: 'unread',
      createdAt: new Date('2026-02-21T08:00:00'),
    },
    
    // 5. BLOCKED - Backend API blocking checkout
    {
      id: 'nudge-5',
      type: 'blocked' as NudgeType,
      severity: 'high' as NudgeSeverity,
      title: 'Checkout Flow blocked for 5 days',
      description: 'Task has been in "Ready" status waiting on Backend API completion.',
      relatedProjectId: 'proj-ecommerce',
      relatedTaskId: 'task-ec-4',
      relatedPersonId: 'user-james',
      aiExplanation: 'Checkout Flow has been ready to start for 5 days but is blocked by Backend API Development. This dependency gap is creating idle time and pushing the critical path. Consider parallel development with mock APIs.',
      suggestedAction: 'Start frontend with mock API responses',
      status: 'unread',
      createdAt: new Date('2026-02-20T14:20:00'),
    },
    
    // 6. CONFLICT - Resource conflict between projects
    {
      id: 'nudge-6',
      type: 'conflict' as NudgeType,
      severity: 'medium' as NudgeSeverity,
      title: 'Alex has conflicting priorities across projects',
      description: 'Alex is assigned critical tasks on both E-Commerce and SaaS Dashboard due same week.',
      relatedProjectId: 'proj-ecommerce',
      relatedTaskId: 'task-ec-3',
      relatedPersonId: 'user-alex',
      aiExplanation: 'Alex is assigned to Frontend Product Catalog (E-Commerce, due March 20) and Real-time Analytics Widgets (SaaS, due March 25). Both are critical path items. If either slips, it impacts two different projects.',
      suggestedAction: 'Move Analytics Widgets to Mike or delay by 1 week',
      status: 'unread',
      createdAt: new Date('2026-02-21T11:00:00'),
    },
    
    // 7. DEPENDENCY_BLOCK - Design blocking development
    {
      id: 'nudge-7',
      type: 'dependency_block' as NudgeType,
      severity: 'medium' as NudgeSeverity,
      title: 'Fitness App development blocked by incomplete designs',
      description: 'Mobile App UI Design is 60% complete but development team is waiting for final screens.',
      relatedProjectId: 'proj-mobile',
      relatedTaskId: 'task-fit-1',
      relatedPersonId: 'user-emma',
      aiExplanation: 'Mobile App UI Design is at risk. Emma has completed core screens but profile and settings screens are pending. Development could start on completed sections while design finishes, but this increases rework risk.',
      suggestedAction: 'Split task: deliver core screens now, polish later',
      status: 'unread',
      createdAt: new Date('2026-02-19T15:30:00'),
    },
    
    // Additional nudges for variety
    {
      id: 'nudge-8',
      type: 'delay_risk' as NudgeType,
      severity: 'low' as NudgeSeverity,
      title: 'Internal Tool time tracking module slightly behind',
      description: 'Task is progressing but may finish 1-2 days late.',
      relatedProjectId: 'proj-internal',
      relatedTaskId: 'task-int-1',
      relatedPersonId: 'user-alex',
      aiExplanation: 'Time Tracking Module is 80% complete but review feedback is taking longer than expected. Low risk since this is not on the critical path.',
      suggestedAction: 'Schedule review session tomorrow',
      status: 'read',
      createdAt: new Date('2026-02-18T10:00:00'),
    },
    
    {
      id: 'nudge-9',
      type: 'overload' as NudgeType,
      severity: 'medium' as NudgeSeverity,
      title: 'James approaching capacity limit',
      description: 'James is at 95% capacity for next 2 weeks.',
      relatedProjectId: 'proj-ecommerce',
      relatedTaskId: 'task-ec-2',
      relatedPersonId: 'user-james',
      aiExplanation: 'While not yet overallocated, James is at 95% capacity. Any additional work or scope creep will push him into overallocation. Monitor closely.',
      suggestedAction: 'No action needed, monitor capacity',
      status: 'dismissed',
      createdAt: new Date('2026-02-17T09:00:00'),
    },
    
    {
      id: 'nudge-10',
      type: 'unassigned' as NudgeType,
      severity: 'low' as NudgeSeverity,
      title: 'Social Features task unassigned but not urgent',
      description: 'Medium priority task without assignee, due in 7 weeks.',
      relatedProjectId: 'proj-mobile',
      relatedTaskId: 'task-fit-3',
      relatedPersonId: undefined,
      aiExplanation: 'Social Features Implementation is unassigned but has a due date 7 weeks out. Lower priority than other unassigned tasks.',
      suggestedAction: 'Assign after current sprint planning',
      status: 'read',
      createdAt: new Date('2026-02-16T14:00:00'),
    },
  ];
};

// ===== WORKLOAD DATA =====
export const createWorkloadData = (users: User[]): WorkloadEntry[] => {
  return [
    {
      personId: 'user-emma',
      personName: 'Emma Wilson',
      allocationPercentage: 125,
      assignedTasks: 4,
      totalEstimatedHours: 75,
      availabilityThisWeek: 0,
      availabilityNextWeek: 5,
    },
    {
      personId: 'user-james',
      personName: 'James Kim',
      allocationPercentage: 95,
      assignedTasks: 2,
      totalEstimatedHours: 60,
      availabilityThisWeek: 8,
      availabilityNextWeek: 15,
    },
    {
      personId: 'user-alex',
      personName: 'Alex Thompson',
      allocationPercentage: 110,
      assignedTasks: 3,
      totalEstimatedHours: 65,
      availabilityThisWeek: 0,
      availabilityNextWeek: 10,
    },
    {
      personId: 'user-lisa',
      personName: 'Lisa Park',
      allocationPercentage: 70,
      assignedTasks: 2,
      totalEstimatedHours: 35,
      availabilityThisWeek: 20,
      availabilityNextWeek: 25,
    },
    {
      personId: 'user-rachel',
      personName: 'Rachel Green',
      allocationPercentage: 60,
      assignedTasks: 2,
      totalEstimatedHours: 30,
      availabilityThisWeek: 25,
      availabilityNextWeek: 30,
    },
    {
      personId: 'user-david',
      personName: 'David Martinez',
      allocationPercentage: 50,
      assignedTasks: 1,
      totalEstimatedHours: 25,
      availabilityThisWeek: 30,
      availabilityNextWeek: 35,
    },
    {
      personId: 'user-mike',
      personName: 'Mike Rodriguez',
      allocationPercentage: 40,
      assignedTasks: 1,
      totalEstimatedHours: 20,
      availabilityThisWeek: 35,
      availabilityNextWeek: 40,
    },
  ];
};

// ===== SCENARIOS =====
export const createRealisticScenarios = (): Scenario[] => {
  return [
    {
      id: 'scenario-1',
      title: 'Emma takes 1-week vacation',
      description: 'Simulate impact of Emma taking vacation next week on all assigned projects.',
      changeType: 'employee_leave',
      status: 'pending',
      proposedChanges: {
        personId: 'user-emma',
        leaveDuration: '5 days',
        affectedProjects: ['proj-mobile', 'proj-ecommerce', 'proj-marketing'],
      },
      impactAnalysis: {
        affectedProjects: ['proj-mobile', 'proj-ecommerce'],
        affectedTasks: ['task-fit-1', 'task-ec-5', 'task-web-3'],
        delayHoursTotal: 40,
        costImpact: 3200,
        recommendations: [
          'Reassign Marketing Website consultation to Rachel',
          'Delay Fitness App UI by 1 week',
          'Have James cover E-Commerce admin dashboard'
        ],
      },
      createdAt: new Date('2026-02-21'),
    },
    {
      id: 'scenario-2',
      title: 'Add Payment Gateway integration',
      description: 'Scope change: Add Stripe payment processing to Checkout Flow.',
      changeType: 'scope_change',
      status: 'pending',
      proposedChanges: {
        taskId: 'task-ec-4',
        additionalHours: 16,
        additionalSkills: ['skill-node'],
      },
      impactAnalysis: {
        affectedProjects: ['proj-ecommerce'],
        affectedTasks: ['task-ec-4'],
        delayHoursTotal: 16,
        costImpact: 1280,
        recommendations: [
          'Extend due date by 2 days',
          'Assign to James who has payment experience'
        ],
      },
      createdAt: new Date('2026-02-20'),
    },
    {
      id: 'scenario-3',
      title: 'Move Alex to Fitness App full-time',
      description: 'Reallocate Alex from SaaS Dashboard to Fitness App for 2 weeks.',
      changeType: 'reallocation',
      status: 'rejected',
      proposedChanges: {
        personId: 'user-alex',
        fromProject: 'proj-saas',
        toProject: 'proj-mobile',
        duration: '2 weeks',
      },
      impactAnalysis: {
        affectedProjects: ['proj-saas', 'proj-mobile'],
        affectedTasks: ['task-saas-2', 'task-fit-3'],
        delayHoursTotal: 20,
        costImpact: 0,
        recommendations: [
          'Real-time Analytics Widgets will delay by 1 week',
          'Fitness App gains 40 hours of capacity'
        ],
      },
      createdAt: new Date('2026-02-18'),
    },
  ];
};

// Export legacy functions for compatibility
export const generateUsers = (count: number = 5): User[] => createRealisticTeam();
export const generateProjects = (count: number = 3): Project[] => createRealisticProjects();
export const generateTasks = (projectId: string, count: number = 5): Task[] => {
  return createRealisticTasks().filter(t => t.projectId === projectId);
};
export const generateSkills = (): Skill[] => createSkillsCatalog();
export const generateNudges = (count: number = 5): Nudge[] => createRealisticNudges();
export const generateWorkloadData = (users: User[]): WorkloadEntry[] => createWorkloadData(users);
export const generateAssignmentSuggestions = (count: number = 3): AssignmentSuggestion[] => {
  return Array.from({ length: count }, () => ({
    personId: faker.string.uuid(),
    score: faker.number.int({ min: 60, max: 98 }),
    reasons: [
      faker.lorem.sentence(),
      faker.lorem.sentence(),
      faker.lorem.sentence(),
    ],
    warnings: faker.datatype.boolean(0.3) ? [faker.lorem.sentence()] : undefined,
  }));
};
export const generateScenarios = (count: number = 2): Scenario[] => createRealisticScenarios();
